### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by kirillandy** [Yiorgoss/nik_mak#2]
Hi! Um... I didn't know how else to contact you so I decided to leave a small message here. Sorry :)
It's Kirill from SLC in Athens. Could you write back at my e-mail address or leave another way I can contact you here?
Cheers!

**Comment by Yiorgoss** [comment]
Wow Kirill I was not expecting this, it's been a while. My personal email is makridakisyiorgos@gmail.com. Im amazed to see another developer coming out of St Lawerence.
Please feel free to email me any time, I'd love to catch up.
